/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps, react-hooks/set-state-in-effect */
import React, { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clock3, FilePlus2, Loader2, LocateFixed, LogIn, LogOut, TimerReset, XCircle } from "lucide-react";
import { toast } from "sonner";
import { supabaseClient } from "../../../lib/supabase/client";
import { isMissingSupabaseRelation } from "../../../lib/supabase/schema-errors";

type Props = { employee: any; portal: "teacher" | "staff" };
const TASK_TYPES = [["additional_duty", "Tugas Tambahan"], ["meeting", "Rapat"], ["event", "Kegiatan Sekolah"], ["emergency", "Kebutuhan Mendesak"], ["replacement", "Pengganti / Backup"], ["other", "Lainnya"]];
const EMPTY = { overtime_date: new Date().toLocaleDateString("en-CA"), planned_start_time: "16:00", planned_end_time: "18:00", check_in_close: "18:00", break_minutes: "0", task_type: "additional_duty", reason: "" };
function shortTime(value?: string) { return String(value || "-").slice(0, 5); }
function formatDate(value?: string) { return value ? new Date(`${value}T00:00:00`).toLocaleDateString("id-ID", { weekday: "long", day: "2-digit", month: "long" }) : "-"; }
function formatMinutes(value?: number) { const minutes = Number(value || 0); return `${Math.floor(minutes / 60)} jam ${minutes % 60} menit`; }
function label(value?: string) { return TASK_TYPES.find(([key]) => key === value)?.[1] || "Tugas tambahan"; }
function currentPosition() { return new Promise<GeolocationPosition>((resolve, reject) => { if (!navigator.geolocation) return reject(new Error("Perangkat tidak mendukung GPS.")); navigator.geolocation.getCurrentPosition(resolve, reject, { enableHighAccuracy: true, timeout: 15000, maximumAge: 0 }); }); }
function errorMessage(error: any) { const message = String(error?.message || error || ""); if (message.includes("OVERTIME_NOT_APPROVED")) return "Lembur belum disetujui."; if (message.includes("OVERTIME_NOT_TODAY")) return "Pencatatan hanya tersedia pada tanggal lembur."; if (message.includes("OVERTIME_CHECK_IN_CLOSED")) return "Batas akhir mulai lembur telah lewat."; if (message.includes("OVERTIME_ALREADY_CHECKED_IN")) return "Mulai lembur sudah tercatat."; if (message.includes("OVERTIME_CHECK_IN_REQUIRED")) return "Catat mulai lembur terlebih dahulu."; if (message.includes("OVERTIME_OVERLAPS_REGULAR_DUTY")) return "Waktu tersebut masih berada dalam jam kerja, shift, atau jadwal mengajar normal sehingga bukan lembur."; if (message.includes("OVERTIME_SCHEDULE_CONFLICT")) return "Jadwal lembur bertabrakan dengan lembur lain yang telah disetujui."; if (message.includes("LOCATION_REQUIRED")) return "GPS diperlukan untuk lembur ini."; if (message.includes("OUTSIDE_GEOFENCE")) return "Anda berada di luar lokasi lembur."; return error?.message || "Data lembur belum dapat diproses."; }

export const EmployeeOvertime: React.FC<Props> = ({ employee, portal }) => {
  const today = new Date().toLocaleDateString("en-CA");
  const [rows, setRows] = useState<any[]>([]);
  const [form, setForm] = useState<any>(EMPTY);
  const [showForm, setShowForm] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [isAvailable, setIsAvailable] = useState(true);
  const [savingId, setSavingId] = useState("");
  const loadRows = async () => { setIsLoading(true); const { data, error } = await supabaseClient.from("employee_overtime").select("*,units(name),attendance_sites(name,address,radius_meters)").eq("employee_id", employee.id).order("overtime_date", { ascending: false }).limit(50); if (error && isMissingSupabaseRelation(error, "employee_overtime")) { setRows([]); setIsAvailable(false); setIsLoading(false); return; } if (error) toast.error("Riwayat lembur belum dapat dimuat", { description: "Silakan coba kembali atau hubungi admin sistem." }); else setIsAvailable(true); setRows((data || []) as any[]); setIsLoading(false); };
  useEffect(() => { void loadRows(); }, [employee.id]);
  const relevantRows = useMemo(() => rows.filter((row) => row.overtime_date >= today || ["pending", "approved"].includes(row.status)).slice(0, 8), [rows, today]);

  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSavingId("request"); try { const { error } = await supabaseClient.from("employee_overtime").insert({ employee_id: employee.id, unit_id: employee.unit_id || null, overtime_date: form.overtime_date, planned_start_time: form.planned_start_time, planned_end_time: form.planned_end_time, check_in_close: form.check_in_close, break_minutes: Number(form.break_minutes), task_type: form.task_type, reason: form.reason.trim(), request_source: "employee", compensation_type: "pending", status: "pending", require_geofence: false }); if (error) throw error; toast.success("Pengajuan lembur dikirim untuk ditinjau."); setForm({ ...EMPTY, overtime_date: today }); setShowForm(false); await loadRows(); } catch (error: any) { toast.error("Pengajuan belum dapat dikirim", { description: error.message }); } finally { setSavingId(""); } };
  const cancel = async (id: string) => { setSavingId(id); const { error } = await supabaseClient.rpc("cancel_employee_overtime_request", { p_overtime_id: id }); if (error) toast.error(errorMessage(error)); else { toast.success("Pengajuan lembur dibatalkan."); await loadRows(); } setSavingId(""); };
  const record = async (row: any, action: "check_in" | "check_out") => { setSavingId(row.id); try { let coordinates: GeolocationCoordinates | null = null; if (row.require_geofence) coordinates = (await currentPosition()).coords; const { data, error } = await supabaseClient.rpc("record_employee_overtime", { p_overtime_id: row.id, p_action: action, p_site_id: row.site_id || null, p_latitude: coordinates?.latitude ?? null, p_longitude: coordinates?.longitude ?? null, p_accuracy_meters: coordinates?.accuracy ?? null, p_device_context: { portal, activity: "overtime", platform: navigator.platform || "unknown" } }); if (error) throw error; const result = data as any; toast.success(action === "check_in" ? "Mulai lembur tercatat." : `Lembur selesai: ${formatMinutes(result?.actual_minutes)}.`); await loadRows(); } catch (error: any) { toast.error(errorMessage(error)); } finally { setSavingId(""); } };

  if (!isAvailable) return null;

  return <section className="rounded-lg border bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 border-b pb-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-md bg-purple-50 text-purple-700"><TimerReset className="h-5 w-5" /></div><div><h2 className="font-bold text-gray-900">Lembur Saya</h2><p className="mt-1 text-xs leading-5 text-gray-500">Kerja tambahan di luar jadwal normal. Pengajar part-time tetap memakai jadwal mengajar sebagai jam kerja normal.</p></div></div><button onClick={() => setShowForm((value) => !value)} className="inline-flex min-h-10 items-center gap-2 rounded-md border bg-white px-3 py-2 text-sm font-bold text-gray-700"><FilePlus2 className="h-4 w-4" /> {showForm ? "Tutup" : "Ajukan Lembur"}</button></div>
    {showForm ? <form onSubmit={submit} className="mt-4 space-y-4 rounded-md border border-purple-200 bg-purple-50/30 p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-xs font-bold text-gray-700">Tanggal<input required type="date" value={form.overtime_date} onChange={(event) => setForm({ ...form, overtime_date: event.target.value })} className="mt-1 h-10 w-full rounded-md border bg-white px-3 font-normal" /></label><label className="text-xs font-bold text-gray-700">Mulai<input required type="time" value={form.planned_start_time} onChange={(event) => setForm({ ...form, planned_start_time: event.target.value })} className="mt-1 h-10 w-full rounded-md border bg-white px-3 font-normal" /></label><label className="text-xs font-bold text-gray-700">Selesai<input required type="time" value={form.planned_end_time} onChange={(event) => setForm({ ...form, planned_end_time: event.target.value })} className="mt-1 h-10 w-full rounded-md border bg-white px-3 font-normal" /></label><label className="text-xs font-bold text-gray-700">Batas akhir mulai<input required type="time" value={form.check_in_close} onChange={(event) => setForm({ ...form, check_in_close: event.target.value })} className="mt-1 h-10 w-full rounded-md border bg-white px-3 font-normal" /></label><label className="text-xs font-bold text-gray-700">Istirahat (menit)<input type="number" min="0" max="240" value={form.break_minutes} onChange={(event) => setForm({ ...form, break_minutes: event.target.value })} className="mt-1 h-10 w-full rounded-md border bg-white px-3 font-normal" /></label><label className="text-xs font-bold text-gray-700">Jenis tugas<select value={form.task_type} onChange={(event) => setForm({ ...form, task_type: event.target.value })} className="mt-1 h-10 w-full rounded-md border bg-white px-3 font-normal">{TASK_TYPES.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label><label className="text-xs font-bold text-gray-700 sm:col-span-2 lg:col-span-3">Alasan dan pekerjaan yang akan diselesaikan<textarea required minLength={10} rows={3} value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} className="mt-1 w-full rounded-md border bg-white p-3 font-normal" /></label></div><div className="flex items-center justify-between gap-3"><p className="text-xs text-purple-800">Pengajuan belum menjadi hak lembur sampai disetujui pimpinan.</p><button disabled={savingId === "request"} className="inline-flex min-h-10 items-center gap-2 rounded-md bg-purple-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{savingId === "request" ? <Loader2 className="h-4 w-4 animate-spin" /> : <FilePlus2 className="h-4 w-4" />} Kirim Pengajuan</button></div></form> : null}
    {isLoading ? <div className="py-10 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin" /></div> : relevantRows.length === 0 ? <div className="py-8 text-center"><CheckCircle2 className="mx-auto mb-2 h-8 w-8 text-emerald-300" /><p className="text-sm font-semibold text-gray-600">Belum ada lembur aktif atau pengajuan menunggu.</p></div> : <div className="divide-y">{relevantRows.map((row) => { const canRecord = row.status === "approved" && row.overtime_date === today; return <article key={row.id} className="py-4 last:pb-0"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-gray-900">{label(row.task_type)}</h3><span className={`rounded-md px-2 py-0.5 text-[10px] font-bold uppercase ${row.status === "completed" ? "bg-emerald-50 text-emerald-700" : row.status === "approved" ? "bg-blue-50 text-blue-700" : row.status === "pending" ? "bg-amber-50 text-amber-700" : "bg-gray-100 text-gray-600"}`}>{row.status}</span></div><p className="mt-1 text-xs text-gray-500">{formatDate(row.overtime_date)} | {shortTime(row.planned_start_time)}-{shortTime(row.planned_end_time)} | {row.units?.name || "Lintas unit"}</p><p className="mt-2 text-xs leading-5 text-gray-600">{row.reason}</p><p className="mt-1 text-[11px] text-purple-700">{row.status === "completed" ? `Realisasi ${formatMinutes(row.actual_minutes)}` : row.status === "approved" ? `Disetujui, kompensasi: ${String(row.compensation_type).replace(/_/g, " ")}. Mulai lebih awal tetap diterima.` : row.review_note || "Menunggu tinjauan pimpinan."}</p></div><div className="flex shrink-0 gap-2">{row.status === "pending" ? <button onClick={() => void cancel(row.id)} disabled={savingId === row.id} className="inline-flex min-h-10 items-center gap-2 rounded-md border px-3 py-2 text-xs font-bold text-red-600"><XCircle className="h-4 w-4" /> Batalkan</button> : null}<button onClick={() => void record(row, "check_in")} disabled={!canRecord || Boolean(row.check_in_at) || savingId === row.id} className="inline-flex min-h-10 items-center gap-2 rounded-md bg-purple-700 px-3 py-2 text-xs font-bold text-white disabled:opacity-40">{savingId === row.id ? <Loader2 className="h-4 w-4 animate-spin" /> : row.require_geofence ? <LocateFixed className="h-4 w-4" /> : <LogIn className="h-4 w-4" />} Mulai</button><button onClick={() => void record(row, "check_out")} disabled={!canRecord || !row.check_in_at || Boolean(row.check_out_at) || savingId === row.id} className="inline-flex min-h-10 items-center gap-2 rounded-md border px-3 py-2 text-xs font-bold text-gray-700 disabled:opacity-40"><LogOut className="h-4 w-4" /> Selesai</button></div></div></article>; })}</div>}
    <div className="mt-4 flex items-start gap-2 rounded-md bg-gray-50 p-3 text-xs text-gray-500"><Clock3 className="mt-0.5 h-4 w-4 shrink-0" /><p>Rapat atau kegiatan tambahan tidak otomatis menjadi lembur. Hak lembur mengikuti persetujuan dan jenis kompensasi yang ditetapkan sekolah.</p></div>
  </section>;
};
