/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import React, { useEffect, useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, Clock3, ExternalLink, Loader2, Receipt, Wallet, XCircle } from "lucide-react";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { PageHeader } from "../../../components/layout/PageHeader";
import { supabaseClient } from "../../../lib/supabase/client";
import { FinanceSectionNav } from "../components/FinanceSectionNav";
import { formatAdmissionDate } from "../../admissions/admissions-config";
import { getDocumentSignedUrl } from "../../../lib/supabase/storage";

const db = supabaseClient as any;

export const SpmbFeesConfig: React.FC = () => {
  const [batches,setBatches]=useState<any[]>([]); const [payments,setPayments]=useState<any[]>([]); const [loading,setLoading]=useState(true);
  const load=async()=>{const [batchResult,paymentResult]=await Promise.all([db.from("admission_batches").select("*,units(name),academic_years(name)").order("registration_start_at",{ascending:false}),db.from("admission_payments").select("*,admissions_applicants(name,registration_number,unit_id,units(name),academic_years(name))").order("created_at",{ascending:false})]);setBatches(batchResult.data||[]);setPayments(paymentResult.data||[]);setLoading(false);};
  useEffect(()=>{void load();},[]);
  const review=async(row:any,approved:boolean)=>{const note=approved?null:window.prompt("Alasan bukti pembayaran ditolak:");if(!approved&&!note)return;const {data:auth}=await supabaseClient.auth.getUser();const {error}=await db.from("admission_payments").update({status:approved?"verified":"rejected",verification_note:note,verified_at:new Date().toISOString(),verified_by:auth.user?.id}).eq("id",row.id);if(error)toast.error(error.message);else{toast.success("Status pembayaran SPMB diperbarui.");await load();}};
  const openProof=async(path:string)=>{try{window.open(await getDocumentSignedUrl(path,300),"_blank","noopener,noreferrer");}catch{toast.error("Bukti pembayaran belum dapat dibuka.");}};
  const stats=useMemo(()=>({expected:batches.filter(x=>x.status==="published").reduce((sum,row)=>sum+Number(row.registration_fee||0)*Number(row.quota||0),0),verified:payments.filter(x=>x.status==="verified").reduce((sum,row)=>sum+Number(row.amount||0),0),pending:payments.filter(x=>["pending","submitted"].includes(x.status)).length}),[batches,payments]);
  if(loading)return <div className="py-28 grid place-items-center"><Loader2 className="w-8 h-8 animate-spin text-emerald-700" /></div>;
  return <div className="space-y-6"><PageHeader title="Keuangan SPMB" description="Rekonsiliasi biaya pendaftaran per gelombang dan penerusan biaya pendidikan setelah calon murid diterima." /><FinanceSectionNav />
    <div className="grid sm:grid-cols-3 gap-4"><Metric icon={Wallet} label="Potensi sesuai kuota" value={money(stats.expected)} /><Metric icon={CheckCircle2} label="Pembayaran terverifikasi" value={money(stats.verified)} /><Metric icon={Clock3} label="Menunggu verifikasi" value={`${stats.pending} transaksi`} /></div>
    <div className="grid lg:grid-cols-[1.5fr_1fr] gap-6"><section className="bg-white border rounded-lg overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold text-lg">Biaya Pendaftaran per Gelombang</h2><p className="text-sm text-slate-600 mt-1">Nominal mengikuti unit dan tahun ajaran pada SPMB.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 border-b"><tr><th className="text-left p-4">Unit / tahun</th><th className="text-left p-4">Gelombang</th><th className="text-left p-4">Biaya</th><th className="text-left p-4">Status</th></tr></thead><tbody className="divide-y">{batches.map(row=><tr key={row.id}><td className="p-4"><p className="font-bold">{row.units?.name}</p><p className="text-xs text-slate-500 mt-1">{row.academic_years?.name}</p></td><td className="p-4"><p className="font-semibold">{row.name}</p><p className="text-xs text-slate-500 mt-1">Tutup {formatAdmissionDate(row.registration_end_at)}</p></td><td className="p-4 font-bold">{money(row.registration_fee)}</td><td className="p-4"><span className={`px-2.5 py-1 rounded-full text-xs font-semibold ${row.status==="published"?"bg-emerald-100 text-emerald-800":"bg-slate-100 text-slate-700"}`}>{row.status==="published"?"Aktif":row.status==="closed"?"Ditutup":"Draf"}</span></td></tr>)}{batches.length===0&&<tr><td colSpan={4} className="p-10 text-center text-slate-500">Belum ada gelombang SPMB.</td></tr>}</tbody></table></div></section><aside className="space-y-4"><Action to="/admissions/settings" title="Atur biaya pendaftaran" detail="Per unit, tahun ajaran, gelombang, dan kuota." /><Action to="/finance/tariffs" title="Atur biaya setelah diterima" detail="SPP, uang pangkal, program tambahan, dan tarif lainnya." /></aside></div>
    <section className="bg-white border rounded-lg overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold text-lg">Verifikasi Pembayaran SPMB</h2><p className="text-sm text-slate-600 mt-1">Antrean ini terpisah dari pembayaran siswa aktif.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 border-b"><tr><th className="text-left p-4">Pendaftar</th><th className="text-left p-4">Unit / tahun</th><th className="text-left p-4">Nominal</th><th className="text-left p-4">Status</th><th className="text-right p-4">Aksi</th></tr></thead><tbody className="divide-y">{payments.map(row=><tr key={row.id}><td className="p-4"><p className="font-bold">{row.admissions_applicants?.name}</p><p className="text-xs text-slate-500 mt-1">{row.admissions_applicants?.registration_number}</p></td><td className="p-4"><p>{row.admissions_applicants?.units?.name}</p><p className="text-xs text-slate-500 mt-1">{row.admissions_applicants?.academic_years?.name}</p></td><td className="p-4 font-bold">{money(row.amount)}</td><td className="p-4"><span className={`px-2.5 py-1 rounded-full text-xs font-semibold ${row.status==="verified"?"bg-emerald-100 text-emerald-800":row.status==="rejected"?"bg-rose-100 text-rose-800":"bg-amber-100 text-amber-800"}`}>{row.status==="verified"?"Terverifikasi":row.status==="rejected"?"Ditolak":"Menunggu"}</span></td><td className="p-4"><div className="flex justify-end gap-2"><button title="Buka bukti" onClick={()=>openProof(row.proof_url)} className="w-9 h-9 grid place-items-center border rounded-md"><ExternalLink className="w-4 h-4" /></button>{row.status!=="verified"&&<button title="Verifikasi" onClick={()=>review(row,true)} className="w-9 h-9 grid place-items-center border rounded-md text-emerald-700"><CheckCircle2 className="w-4 h-4" /></button>}{row.status!=="rejected"&&<button title="Tolak bukti" onClick={()=>review(row,false)} className="w-9 h-9 grid place-items-center border rounded-md text-rose-700"><XCircle className="w-4 h-4" /></button>}</div></td></tr>)}{payments.length===0&&<tr><td colSpan={5} className="p-10 text-center text-slate-500">Belum ada pembayaran SPMB.</td></tr>}</tbody></table></div></section>
  </div>;
};
const money=(value:number)=>Number(value||0).toLocaleString("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const Metric=({icon:Icon,label,value}:{icon:React.ElementType;label:string;value:string})=><div className="bg-white border rounded-lg p-5"><Icon className="w-5 h-5 text-emerald-700" /><p className="text-xl font-bold mt-4">{value}</p><p className="text-sm text-slate-600 mt-1">{label}</p></div>;
const Action=({to,title,detail}:{to:string;title:string;detail:string})=><Link to={to} className="bg-white border rounded-lg p-5 flex items-center gap-4 hover:border-emerald-300"><div className="w-10 h-10 bg-slate-100 rounded-md grid place-items-center"><Receipt className="w-5 h-5 text-slate-600" /></div><div className="flex-1"><p className="font-bold">{title}</p><p className="text-sm text-slate-600 mt-1">{detail}</p></div><ArrowRight className="w-4 h-4 text-slate-400" /></Link>;
