/* eslint-disable @typescript-eslint/no-explicit-any */
import React, { useEffect, useState } from "react";
import { FileBarChart, LayoutDashboard, LogOut, Menu, Settings, Users, X } from "lucide-react";
import { Link, Navigate, Outlet, useLocation, useNavigate } from "react-router-dom";
import { BrandLogo } from "../../components/common/BrandLogo";
import { supabaseClient } from "../../lib/supabase/client";

const db = supabaseClient as any;

export const AdminSpmbLayout: React.FC = () => {
  const location = useLocation(); const navigate = useNavigate();
  const [employee,setEmployee] = useState<any>(null); const [loading,setLoading] = useState(true); const [allowed,setAllowed] = useState(true); const [mobile,setMobile] = useState(false);
  useEffect(() => { supabaseClient.auth.getSession().then(async ({data}) => { if(!data.session){setAllowed(false);setLoading(false);return;} const [emp,access] = await Promise.all([db.from("employees").select("full_name,position,status").eq("user_id",data.session.user.id).maybeSingle(),db.rpc("admission_is_manager",{target_unit_id:null})]); setEmployee(emp.data||{full_name:data.session.user.user_metadata?.full_name||"Admin SPMB",position:"Panitia SPMB"}); setAllowed(access.data !== false); setLoading(false); }); },[]);
  if(loading)return <div className="min-h-screen grid place-items-center bg-slate-50"><div className="w-8 h-8 border-2 border-emerald-700 border-t-transparent rounded-full animate-spin" /></div>;
  if(!allowed)return <Navigate to="/admin-spmb/login" replace />;
  const nav=[{name:"Ringkasan",path:"/admin-spmb",icon:LayoutDashboard},{name:"Pendaftar",path:"/admin-spmb/applicants",icon:Users},{name:"Laporan Mutu",path:"/admin-spmb/reports",icon:FileBarChart},{name:"Pengaturan",path:"/admin-spmb/settings",icon:Settings}];
  const active=(path:string)=>location.pathname===path||(path!=="/admin-spmb"&&location.pathname.startsWith(path));
  const logout=async()=>{await supabaseClient.auth.signOut();navigate("/admin-spmb/login",{replace:true});};
  return <div className="min-h-screen bg-slate-50 text-slate-950 flex"><aside className={`fixed lg:sticky top-0 z-40 h-screen w-64 bg-white border-r flex flex-col transition-transform ${mobile?"translate-x-0":"-translate-x-full lg:translate-x-0"}`}><div className="h-16 px-5 border-b flex items-center justify-between"><BrandLogo textClassName="font-bold text-base text-slate-950" /><button onClick={()=>setMobile(false)} className="lg:hidden w-9 h-9 grid place-items-center"><X className="w-5 h-5" /></button></div><div className="p-4 border-b"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-md bg-emerald-50 text-emerald-700 grid place-items-center font-bold">{employee?.full_name?.charAt(0)||"A"}</div><div className="min-w-0"><p className="font-bold text-sm truncate">{employee?.full_name}</p><p className="text-xs text-slate-500 truncate">{employee?.position||"Panitia SPMB"}</p></div></div></div><nav className="p-3 flex-1 space-y-1">{nav.map(({name,path,icon:Icon})=><Link onClick={()=>setMobile(false)} key={path} to={path} className={`h-11 px-3 rounded-md flex items-center gap-3 text-sm font-semibold ${active(path)?"bg-emerald-50 text-emerald-800":"text-slate-600 hover:bg-slate-100 hover:text-slate-900"}`}><Icon className="w-5 h-5" />{name}</Link>)}</nav><div className="p-3 border-t"><button onClick={logout} className="w-full h-11 px-3 rounded-md flex items-center gap-3 text-sm font-semibold text-slate-600 hover:bg-rose-50 hover:text-rose-700"><LogOut className="w-5 h-5" />Keluar</button></div></aside>{mobile&&<button className="fixed inset-0 z-30 bg-black/20 lg:hidden" onClick={()=>setMobile(false)} aria-label="Tutup menu" />}<div className="flex-1 min-w-0"><header className="lg:hidden sticky top-0 z-20 h-16 bg-white border-b px-4 flex items-center gap-3"><button onClick={()=>setMobile(true)} className="w-9 h-9 border rounded-md grid place-items-center"><Menu className="w-5 h-5" /></button><span className="font-bold">Portal Panitia SPMB</span></header><main className="p-4 sm:p-6 xl:p-8 max-w-[1440px] mx-auto"><Outlet /></main></div></div>;
};
