/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import React, { useEffect, useState } from "react";
import { CheckCircle2, Loader2, Plus, Save, Settings2 } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "../../../components/layout/PageHeader";
import { supabaseClient } from "../../../lib/supabase/client";
import { formatAdmissionDate } from "../admissions-config";

const db = supabaseClient as any;
const emptyBatch = { unit_id: "", academic_year_id: "", name: "Gelombang 1", registration_start_at: "", registration_end_at: "", quota: "", registration_fee: "0", announcement_at: "", notes: "", status: "draft" };

export const AdmissionsSettings: React.FC = () => {
  const [units,setUnits] = useState<any[]>([]); const [years,setYears] = useState<any[]>([]); const [batches,setBatches] = useState<any[]>([]);
  const [form,setForm] = useState(emptyBatch); const [loading,setLoading] = useState(true); const [saving,setSaving] = useState(false);
  const [scope,setScope] = useState({unit_id:"",academic_year_id:""});
  const [policy,setPolicy] = useState({contact_name:"",contact_phone:"",selection_policy:"",announcement_message:"",is_public:true});

  const load = async () => { setLoading(true); const [u,y,b] = await Promise.all([db.from("units").select("id,name").order("name"),db.from("academic_years").select("id,name,is_active").order("start_date",{ascending:false}),db.from("admission_batches").select("*,units(name),academic_years(name)").order("registration_start_at",{ascending:false})]); setUnits(u.data||[]); setYears(y.data||[]); setBatches(b.data||[]); setLoading(false); };
  useEffect(() => { void load(); }, []);
  useEffect(() => { if(!scope.unit_id||!scope.academic_year_id) return; db.from("admission_settings").select("*").eq("unit_id",scope.unit_id).eq("academic_year_id",scope.academic_year_id).maybeSingle().then(({data}:any) => setPolicy(data ? {contact_name:data.contact_name||"",contact_phone:data.contact_phone||"",selection_policy:data.selection_policy||"",announcement_message:data.announcement_message||"",is_public:data.is_public} : {contact_name:"",contact_phone:"",selection_policy:"",announcement_message:"",is_public:true})); },[scope]);
  const set = (key:string,value:any) => setForm((current) => ({...current,[key]:value}));
  const create = async () => { if(!form.unit_id||!form.academic_year_id||!form.name.trim()||!form.registration_start_at||!form.registration_end_at){toast.error("Lengkapi unit, tahun ajaran, nama, dan periode pendaftaran.");return;} if(new Date(form.registration_end_at)<=new Date(form.registration_start_at)){toast.error("Tanggal penutupan harus setelah tanggal pembukaan.");return;} setSaving(true); const {error}=await db.from("admission_batches").insert({...form,quota:form.quota?Number(form.quota):null,registration_fee:Number(form.registration_fee||0),announcement_at:form.announcement_at||null});setSaving(false);if(error)toast.error(error.message);else{toast.success("Gelombang pendaftaran dibuat.");setForm(emptyBatch);await load();}};
  const updateStatus = async (row:any,status:string) => { const {error}=await db.from("admission_batches").update({status}).eq("id",row.id);if(error)toast.error(error.message);else{toast.success(status==="published"?"Gelombang diterbitkan ke portal publik.":"Status gelombang diperbarui.");await load();}};
  const savePolicy = async () => { if(!scope.unit_id||!scope.academic_year_id){toast.error("Pilih unit dan tahun ajaran.");return;} setSaving(true); const {error}=await db.from("admission_settings").upsert({...policy,...scope},{onConflict:"unit_id,academic_year_id"});setSaving(false);if(error)toast.error(error.message);else toast.success("Kebijakan dan kontak SPMB tersimpan."); };
  const input="w-full h-10 px-3 border rounded-md bg-white";

  if(loading)return <div className="py-28 grid place-items-center"><Loader2 className="w-8 h-8 animate-spin text-emerald-700" /></div>;
  return <div className="space-y-6"><PageHeader title="Pengaturan SPMB" description="Kelola gelombang, kuota, biaya, kontak panitia, dan kebijakan secara terpisah untuk setiap unit dan tahun ajaran." />
    <section className="bg-white border rounded-lg p-5 sm:p-6"><div className="flex items-center gap-3 mb-5"><div className="w-10 h-10 bg-emerald-50 text-emerald-700 rounded-md grid place-items-center"><Plus className="w-5 h-5" /></div><div><h2 className="font-bold text-lg">Buat Gelombang Pendaftaran</h2><p className="text-sm text-slate-600">Gelombang berstatus diterbitkan akan muncul di formulir orang tua.</p></div></div><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4"><Field label="Unit *"><select className={input} value={form.unit_id} onChange={(e)=>set("unit_id",e.target.value)}><option value="">Pilih unit</option>{units.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Tahun ajaran *"><select className={input} value={form.academic_year_id} onChange={(e)=>set("academic_year_id",e.target.value)}><option value="">Pilih tahun</option>{years.map(x=><option key={x.id} value={x.id}>{x.name}{x.is_active?" · aktif":""}</option>)}</select></Field><Field label="Nama gelombang *"><input className={input} value={form.name} onChange={(e)=>set("name",e.target.value)} /></Field><Field label="Status awal"><select className={input} value={form.status} onChange={(e)=>set("status",e.target.value)}><option value="draft">Draf</option><option value="published">Diterbitkan</option></select></Field><Field label="Mulai pendaftaran *"><input type="datetime-local" className={input} value={form.registration_start_at} onChange={(e)=>set("registration_start_at",e.target.value)} /></Field><Field label="Tutup pendaftaran *"><input type="datetime-local" className={input} value={form.registration_end_at} onChange={(e)=>set("registration_end_at",e.target.value)} /></Field><Field label="Rencana pengumuman"><input type="datetime-local" className={input} value={form.announcement_at} onChange={(e)=>set("announcement_at",e.target.value)} /></Field><Field label="Kuota"><input type="number" min="1" className={input} value={form.quota} onChange={(e)=>set("quota",e.target.value)} placeholder="Tidak dibatasi" /></Field><Field label="Biaya pendaftaran"><input type="number" min="0" className={input} value={form.registration_fee} onChange={(e)=>set("registration_fee",e.target.value)} /></Field><label className="text-sm font-semibold md:col-span-2 xl:col-span-3">Catatan internal<textarea className="w-full min-h-20 mt-2 p-3 border rounded-md" value={form.notes} onChange={(e)=>set("notes",e.target.value)} /></label></div><button onClick={create} disabled={saving} className="mt-5 h-10 px-4 bg-emerald-700 text-white rounded-md font-semibold flex items-center gap-2"><Save className="w-4 h-4" />Simpan Gelombang</button></section>
    <section className="bg-white border rounded-lg overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold text-lg">Gelombang per Unit</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 border-b"><tr><th className="text-left p-4">Unit / tahun</th><th className="text-left p-4">Gelombang</th><th className="text-left p-4">Periode</th><th className="text-left p-4">Kuota / biaya</th><th className="text-left p-4">Status</th><th className="text-right p-4">Aksi</th></tr></thead><tbody className="divide-y">{batches.map(row=><tr key={row.id}><td className="p-4"><p className="font-bold">{row.units?.name}</p><p className="text-xs text-slate-500 mt-1">{row.academic_years?.name}</p></td><td className="p-4 font-semibold">{row.name}</td><td className="p-4"><p>{formatAdmissionDate(row.registration_start_at)}</p><p className="text-xs text-slate-500 mt-1">s.d. {formatAdmissionDate(row.registration_end_at)}</p></td><td className="p-4"><p>{row.quota?`${row.quota} murid`:"Tanpa batas"}</p><p className="text-xs text-slate-500 mt-1">{Number(row.registration_fee).toLocaleString("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0})}</p></td><td className="p-4"><span className={`px-2.5 py-1 rounded-full text-xs font-semibold ${row.status==="published"?"bg-emerald-100 text-emerald-800":row.status==="closed"?"bg-slate-200 text-slate-700":"bg-amber-100 text-amber-800"}`}>{row.status==="published"?"Diterbitkan":row.status==="closed"?"Ditutup":"Draf"}</span></td><td className="p-4"><div className="flex justify-end gap-2">{row.status!=="published"&&<button onClick={()=>updateStatus(row,"published")} className="h-9 px-3 border rounded-md text-xs font-semibold text-emerald-700">Terbitkan</button>}{row.status!=="closed"&&<button onClick={()=>updateStatus(row,"closed")} className="h-9 px-3 border rounded-md text-xs font-semibold">Tutup</button>}</div></td></tr>)}{batches.length===0&&<tr><td colSpan={6} className="p-10 text-center text-slate-500">Belum ada gelombang pendaftaran.</td></tr>}</tbody></table></div></section>
    <section className="bg-white border rounded-lg p-5 sm:p-6"><div className="flex items-center gap-3"><Settings2 className="w-5 h-5 text-emerald-700" /><div><h2 className="font-bold text-lg">Kebijakan dan Kontak Unit</h2><p className="text-sm text-slate-600">Informasi publik mengikuti unit dan tahun ajaran.</p></div></div><div className="grid md:grid-cols-2 gap-4 mt-5"><Field label="Unit"><select className={input} value={scope.unit_id} onChange={(e)=>setScope(v=>({...v,unit_id:e.target.value}))}><option value="">Pilih unit</option>{units.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Tahun ajaran"><select className={input} value={scope.academic_year_id} onChange={(e)=>setScope(v=>({...v,academic_year_id:e.target.value}))}><option value="">Pilih tahun</option>{years.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Nama kontak panitia"><input className={input} value={policy.contact_name} onChange={(e)=>setPolicy(v=>({...v,contact_name:e.target.value}))} /></Field><Field label="WhatsApp panitia"><input className={input} value={policy.contact_phone} onChange={(e)=>setPolicy(v=>({...v,contact_phone:e.target.value}))} /></Field><label className="text-sm font-semibold">Kebijakan seleksi<textarea className="w-full min-h-24 mt-2 p-3 border rounded-md" value={policy.selection_policy} onChange={(e)=>setPolicy(v=>({...v,selection_policy:e.target.value}))} /></label><label className="text-sm font-semibold">Pesan pengumuman<textarea className="w-full min-h-24 mt-2 p-3 border rounded-md" value={policy.announcement_message} onChange={(e)=>setPolicy(v=>({...v,announcement_message:e.target.value}))} /></label><label className="md:col-span-2 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={policy.is_public} onChange={(e)=>setPolicy(v=>({...v,is_public:e.target.checked}))} />Tampilkan informasi ini di portal publik</label></div><button onClick={savePolicy} disabled={saving} className="mt-5 h-10 px-4 bg-slate-900 text-white rounded-md font-semibold flex items-center gap-2"><CheckCircle2 className="w-4 h-4" />Simpan Kebijakan</button></section>
  </div>;
};

const Field=({label,children}:{label:string;children:React.ReactNode})=><label className="text-sm font-semibold">{label}<span className="block mt-2">{children}</span></label>;
