/* eslint-disable @typescript-eslint/no-explicit-any */
import React, { useEffect, useState } from "react";
import { useTable } from "@refinedev/core";
import { Link } from "react-router-dom";
import { ChevronLeft, ChevronRight, Eye, Inbox, Plus, Search } from "lucide-react";
import { PageHeader } from "../../../components/layout/PageHeader";
import { useCurrentUnit } from "../../../app/providers/UnitProvider";
import { OfficeSectionNav } from "../components/OfficeSectionNav";

const labels: Record<string, string> = { logged: "Baru dicatat", dispositioned: "Didisposisikan", in_progress: "Diproses", completed: "Selesai", archived: "Diarsipkan" };

export const IncomingMailList: React.FC = () => {
  const { activeUnitId } = useCurrentUnit();
  const [search, setSearch] = useState("");
  const [debounced, setDebounced] = useState("");
  const [status, setStatus] = useState("");
  useEffect(() => { const timer = setTimeout(() => setDebounced(search), 350); return () => clearTimeout(timer); }, [search]);
  const filters: any[] = [{ field: "type", operator: "eq", value: "incoming" }];
  if (activeUnitId) filters.push({ field: "unit_id", operator: "eq", value: activeUnitId });
  if (status) filters.push({ field: "status", operator: "eq", value: status });
  if (debounced) filters.push({ operator: "or", value: [{ field: "agenda_number", operator: "contains", value: debounced }, { field: "mail_number", operator: "contains", value: debounced }, { field: "title", operator: "contains", value: debounced }, { field: "sender", operator: "contains", value: debounced }] });
  const { tableQueryResult, current, setCurrent, pageCount } = useTable({ resource: "mail_records", filters: { permanent: filters }, pagination: { current: 1, pageSize: 15 }, sorters: { initial: [{ field: "received_date", order: "desc" }] }, meta: { select: "*,units(name),handler:employees!mail_records_handled_by_employee_id_fkey(full_name)" } });
  const rows = tableQueryResult.data?.data || [];
  return <div className="space-y-6"><PageHeader title="Agenda Surat Masuk" description="Catat penerimaan, klasifikasi, tenggat respons, PIC, lampiran, dan disposisi surat setiap unit." action={<Link to="/mail/incoming/create" className="flex items-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground"><Plus className="h-4 w-4" />Catat Surat</Link>} /><OfficeSectionNav />
    <div className="flex flex-col gap-3 rounded-lg border bg-card p-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari agenda, nomor surat, perihal, atau pengirim" className="h-10 w-full rounded-md border bg-background pl-9 pr-3 text-sm" /></label><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-10 rounded-md border bg-background px-3 text-sm font-semibold"><option value="">Semua status</option><option value="logged">Baru dicatat</option><option value="dispositioned">Didisposisikan</option><option value="in_progress">Diproses</option><option value="completed">Selesai</option><option value="archived">Diarsipkan</option></select></div>
    <div className="overflow-hidden rounded-lg border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b bg-muted/40 text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3">Agenda / surat</th><th className="px-4 py-3">Pengirim & perihal</th><th className="px-4 py-3">Unit / PIC</th><th className="px-4 py-3">Tenggat</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Buka</th></tr></thead><tbody className="divide-y">{tableQueryResult.isLoading ? <tr><td colSpan={6} className="h-48 text-center">Memuat agenda surat...</td></tr> : rows.map((row: any) => <tr key={row.id} className="hover:bg-muted/20"><td className="px-4 py-3"><p className="font-bold text-primary">{row.agenda_number || "Menunggu nomor agenda"}</p><p className="mt-1 text-xs text-muted-foreground">{row.mail_number} - {new Date(row.mail_date).toLocaleDateString("id-ID")}</p></td><td className="px-4 py-3"><p className="font-semibold">{row.sender}</p><p className="mt-1 max-w-md truncate text-xs text-muted-foreground">{row.title}</p></td><td className="px-4 py-3"><p>{row.units?.name || "Lintas unit"}</p><p className="mt-1 text-xs text-muted-foreground">{row.handler?.full_name || "PIC belum ditentukan"}</p></td><td className="px-4 py-3">{row.response_required ? <span className="font-semibold text-amber-700">{row.due_date ? new Date(row.due_date).toLocaleDateString("id-ID") : "Perlu respons"}</span> : <span className="text-muted-foreground">Tidak ada</span>}</td><td className="px-4 py-3"><span className="rounded bg-muted px-2 py-1 text-xs font-semibold">{labels[row.status] || row.status}</span></td><td className="px-4 py-3 text-right"><Link to={`/mail/show/${row.id}`} className="inline-flex rounded-md border p-2 text-primary" title="Buka detail"><Eye className="h-4 w-4" /></Link></td></tr>)}{!tableQueryResult.isLoading && rows.length === 0 && <tr><td colSpan={6} className="h-48 text-center"><Inbox className="mx-auto mb-2 h-8 w-8 text-muted-foreground/40" />Belum ada surat masuk sesuai filter.</td></tr>}</tbody></table></div>{pageCount > 1 && <div className="flex items-center justify-between border-t px-4 py-3 text-sm"><span>Halaman {current} dari {pageCount}</span><div className="flex gap-2"><button disabled={current === 1} onClick={() => setCurrent(current - 1)} className="rounded border p-2 disabled:opacity-40"><ChevronLeft className="h-4 w-4" /></button><button disabled={current === pageCount} onClick={() => setCurrent(current + 1)} className="rounded border p-2 disabled:opacity-40"><ChevronRight className="h-4 w-4" /></button></div></div>}</div>
  </div>;
};
