/* eslint-disable @typescript-eslint/no-explicit-any */
import React, { useState } from "react";
import { useCreate, useList, useShow, useUpdate } from "@refinedev/core";
import { useNavigate } from "react-router-dom";
import { Archive, ArrowLeft, CalendarClock, CheckCircle2, Download, FileSignature, Loader2, LockKeyhole, Send, Workflow } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "../../../components/layout/PageHeader";
import { getDocumentSignedUrl } from "../../../lib/supabase/storage";
import { useCurrentUser } from "../../../hooks/useAuth";
import { OfficeSectionNav } from "../components/OfficeSectionNav";

const statusLabels: Record<string, string> = { logged: "Tercatat", dispositioned: "Didisposisikan", in_progress: "Diproses", awaiting_approval: "Menunggu Persetujuan", approved: "Disetujui", sent: "Terkirim", completed: "Selesai", archived: "Diarsipkan", rejected: "Ditolak" };

export const MailShow: React.FC = () => {
  const navigate = useNavigate();
  const { user } = useCurrentUser();
  const { queryResult } = useShow({ resource: "mail_records", meta: { select: "*,units(name),handler:employees!mail_records_handled_by_employee_id_fkey(full_name),approver:employees!mail_records_approved_by_employee_id_fkey(full_name)" } });
  const mail: any = queryResult.data?.data;
  const { data: employeeData } = useList({ resource: "employees", filters: user?.id ? [{ field: "user_id", operator: "eq", value: user.id }] : [], pagination: { mode: "off" }, queryOptions: { enabled: Boolean(user?.id) } });
  const currentEmployee: any = employeeData?.data?.[0];
  const { data: employees } = useList({ resource: "employees", filters: [{ field: "status", operator: "eq", value: "active" }], pagination: { mode: "off" }, sorters: [{ field: "full_name", order: "asc" }] });
  const { data: dispositionData, refetch: refetchDispositions } = useList({ resource: "mail_dispositions", filters: mail?.id ? [{ field: "mail_id", operator: "eq", value: mail.id }] : [], pagination: { mode: "off" }, sorters: [{ field: "created_at", order: "desc" }], meta: { select: "*,from_employee:employees!mail_dispositions_from_employee_id_fkey(full_name),to_employee:employees!mail_dispositions_to_employee_id_fkey(full_name)" }, queryOptions: { enabled: Boolean(mail?.id) } });
  const { mutate: createDisposition, isLoading: isCreating } = useCreate();
  const { mutate: updateMail, isLoading: isUpdating } = useUpdate();
  const [form, setForm] = useState({ to_employee_id: "", instruction: "", disposition_type: "follow_up", priority: "normal", due_date: "" });
  const [responseNote, setResponseNote] = useState("");
  const [attachmentUrl, setAttachmentUrl] = useState("");

  React.useEffect(() => { if (mail?.attachment_path) getDocumentSignedUrl(mail.attachment_path, 900).then(setAttachmentUrl).catch(() => setAttachmentUrl("")); }, [mail?.attachment_path]);

  const create = (event: React.FormEvent) => {
    event.preventDefault();
    if (!form.to_employee_id || form.instruction.trim().length < 5) return toast.error("Pilih penerima dan isi instruksi minimal 5 karakter.");
    createDisposition({ resource: "mail_dispositions", values: { ...form, mail_id: mail.id, from_employee_id: currentEmployee?.id || null, due_date: form.due_date || null } }, { onSuccess: () => { updateMail({ resource: "mail_records", id: mail.id, values: { status: "dispositioned", handled_by_employee_id: form.to_employee_id } }); toast.success("Disposisi berhasil dikirim."); setForm({ to_employee_id: "", instruction: "", disposition_type: "follow_up", priority: "normal", due_date: "" }); refetchDispositions(); }, onError: (error) => toast.error("Disposisi gagal dikirim", { description: error.message }) });
  };

  const setStatus = (status: string) => {
    const values: Record<string, unknown> = { status };
    if (status === "approved") { values.approved_by_employee_id = currentEmployee?.id || null; values.approved_at = new Date().toISOString(); }
    if (status === "sent") values.sent_at = new Date().toISOString();
    if (status === "archived") { values.archived_by_employee_id = currentEmployee?.id || null; values.archived_at = new Date().toISOString(); }
    if (status === "rejected") values.rejection_reason = responseNote || "Perlu perbaikan";
    updateMail({ resource: "mail_records", id: mail.id, values }, { onSuccess: () => { toast.success(`Status surat: ${statusLabels[status]}.`); queryResult.refetch(); } });
  };

  if (queryResult.isLoading) return <div className="flex h-64 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin" /></div>;
  if (!mail) return <div className="p-12 text-center">Surat tidak ditemukan.</div>;
  const dispositions = dispositionData?.data || [];
  const isOutgoing = mail.type === "outgoing";

  return <div className="space-y-6">
    <PageHeader title={isOutgoing ? "Detail Surat Keluar" : "Detail Surat Masuk"} description={`${mail.agenda_number || "Nomor agenda belum terbentuk"} - ${mail.mail_number}`} action={<button onClick={() => navigate(isOutgoing ? "/mail/outgoing" : "/mail/incoming")} className="flex items-center gap-2 rounded-md border px-4 py-2 text-sm font-bold"><ArrowLeft className="h-4 w-4" />Kembali</button>} />
    <OfficeSectionNav />
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.3fr)_390px]">
      <div className="space-y-6"><section className="rounded-lg border bg-card p-5"><div className="flex flex-col gap-4 border-b pb-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded bg-primary/10 px-2 py-1 text-xs font-bold text-primary">{mail.agenda_number || "AGENDA"}</span><span className="rounded bg-muted px-2 py-1 text-xs font-semibold">{statusLabels[mail.status] || mail.status}</span>{mail.confidentiality !== "public" && <span className="flex items-center gap-1 rounded bg-amber-50 px-2 py-1 text-xs font-semibold text-amber-700"><LockKeyhole className="h-3 w-3" />{mail.confidentiality}</span>}</div><h2 className="mt-3 text-xl font-bold">{mail.title}</h2><p className="mt-1 text-sm text-muted-foreground">{isOutgoing ? `Kepada ${mail.recipient}` : `Dari ${mail.sender}`}</p></div><div className="text-right text-sm"><p className="font-semibold">{new Date(mail.mail_date).toLocaleDateString("id-ID", { day: "numeric", month: "long", year: "numeric" })}</p><p className="text-xs text-muted-foreground">{mail.units?.name || "Lintas unit"}</p></div></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-3"><div><dt className="text-xs font-semibold text-muted-foreground">Nomor surat</dt><dd className="mt-1 font-medium">{mail.mail_number}</dd></div><div><dt className="text-xs font-semibold text-muted-foreground">Klasifikasi</dt><dd className="mt-1 font-medium">{mail.classification_code || "Belum diklasifikasi"}</dd></div><div><dt className="text-xs font-semibold text-muted-foreground">Media diterima/dikirim</dt><dd className="mt-1 font-medium capitalize">{mail.channel}</dd></div><div><dt className="text-xs font-semibold text-muted-foreground">Prioritas</dt><dd className="mt-1 font-medium capitalize">{mail.priority}</dd></div><div><dt className="text-xs font-semibold text-muted-foreground">PIC</dt><dd className="mt-1 font-medium">{mail.handler?.full_name || "Belum ditentukan"}</dd></div><div><dt className="text-xs font-semibold text-muted-foreground">Tenggat respons</dt><dd className="mt-1 font-medium">{mail.due_date ? new Date(mail.due_date).toLocaleDateString("id-ID") : "Tidak ada"}</dd></div></dl>{mail.description && <div className="mt-5 rounded-md bg-muted/40 p-4 text-sm leading-6">{mail.description}</div>}{mail.attachment_path && <div className="mt-4 flex items-center justify-between rounded-md border p-3"><div><p className="text-sm font-semibold">{mail.attachment_name || "Lampiran surat"}</p><p className="text-xs text-muted-foreground">{mail.attachment_mime_type} {mail.attachment_size ? `- ${(mail.attachment_size / 1024).toFixed(1)} KB` : ""}</p></div>{attachmentUrl && <a href={attachmentUrl} target="_blank" rel="noreferrer" className="rounded-md border p-2" title="Buka lampiran"><Download className="h-4 w-4" /></a>}</div>}</section>
      <section className="overflow-hidden rounded-lg border bg-card"><div className="border-b px-5 py-4"><h2 className="font-bold">Jejak Disposisi</h2><p className="text-xs text-muted-foreground">Instruksi, penerima, tenggat, dan hasil tindak lanjut.</p></div>{dispositions.length === 0 ? <div className="p-10 text-center text-sm text-muted-foreground">Surat ini belum memiliki disposisi.</div> : <div className="divide-y">{dispositions.map((item: any) => <div key={item.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{item.to_employee?.full_name || "Penerima tidak tersedia"}</p><p className="mt-1 text-xs text-muted-foreground">Dari {item.from_employee?.full_name || "Tata Usaha"} - {item.disposition_type}</p></div><span className={`rounded px-2 py-1 text-xs font-bold ${item.status === "completed" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{item.status}</span></div><p className="mt-3 rounded-md bg-muted/40 p-3 text-sm">{item.instruction}</p>{item.response_note && <p className="mt-2 text-sm"><strong>Hasil:</strong> {item.response_note}</p>}<p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground"><CalendarClock className="h-3.5 w-3.5" />{item.due_date ? `Tenggat ${new Date(item.due_date).toLocaleDateString("id-ID")}` : "Tanpa tenggat"}</p></div>)}</div>}</section></div>
      <aside className="self-start space-y-5 xl:sticky xl:top-20"><section className="rounded-lg border bg-card p-5"><div className="mb-4 flex items-center gap-2"><FileSignature className="h-5 w-5 text-primary" /><h2 className="font-bold">Buat Disposisi</h2></div><form onSubmit={create} className="space-y-3"><label className="block text-sm font-semibold">Penerima<select value={form.to_employee_id} onChange={(e) => setForm({ ...form, to_employee_id: e.target.value })} className="mt-1.5 h-10 w-full rounded-md border bg-background px-3 font-normal"><option value="">Pilih pegawai</option>{employees?.data?.map((employee: any) => <option key={employee.id} value={employee.id}>{employee.full_name} - {employee.position || "Pegawai"}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold">Jenis<select value={form.disposition_type} onChange={(e) => setForm({ ...form, disposition_type: e.target.value })} className="mt-1.5 h-9 w-full rounded-md border bg-background px-2 text-sm font-normal"><option value="information">Diketahui</option><option value="follow_up">Tindak lanjuti</option><option value="represent">Wakili</option><option value="coordinate">Koordinasikan</option><option value="file">Arsipkan</option></select></label><label className="text-xs font-bold">Prioritas<select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })} className="mt-1.5 h-9 w-full rounded-md border bg-background px-2 text-sm font-normal"><option value="normal">Normal</option><option value="high">Tinggi</option><option value="urgent">Darurat</option><option value="low">Rendah</option></select></label></div><label className="block text-sm font-semibold">Tenggat<input type="date" value={form.due_date} onChange={(e) => setForm({ ...form, due_date: e.target.value })} className="mt-1.5 h-10 w-full rounded-md border bg-background px-3 font-normal" /></label><label className="block text-sm font-semibold">Instruksi<textarea rows={4} value={form.instruction} onChange={(e) => setForm({ ...form, instruction: e.target.value })} className="mt-1.5 w-full rounded-md border bg-background p-3 font-normal" /></label><button disabled={isCreating} className="flex w-full items-center justify-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground disabled:opacity-60">{isCreating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Workflow className="h-4 w-4" />}Kirim Disposisi</button></form></section>
      <section className="rounded-lg border bg-card p-5"><h2 className="font-bold">Proses Surat</h2><p className="mt-1 text-xs text-muted-foreground">Gunakan tindakan sesuai tahap administrasi yang benar.</p><textarea value={responseNote} onChange={(e) => setResponseNote(e.target.value)} rows={2} placeholder="Catatan keputusan (bila diperlukan)" className="mt-4 w-full rounded-md border bg-background p-3 text-sm" /><div className="mt-3 grid grid-cols-2 gap-2">{isOutgoing ? <><button onClick={() => setStatus("approved")} disabled={isUpdating} className="flex items-center justify-center gap-1 rounded-md border px-3 py-2 text-sm font-bold"><CheckCircle2 className="h-4 w-4" />Setujui</button><button onClick={() => setStatus("sent")} disabled={isUpdating} className="flex items-center justify-center gap-1 rounded-md bg-primary px-3 py-2 text-sm font-bold text-primary-foreground"><Send className="h-4 w-4" />Terkirim</button></> : <button onClick={() => setStatus("completed")} disabled={isUpdating} className="col-span-2 flex items-center justify-center gap-1 rounded-md bg-primary px-3 py-2 text-sm font-bold text-primary-foreground"><CheckCircle2 className="h-4 w-4" />Tandai Selesai</button>}<button onClick={() => setStatus("archived")} disabled={isUpdating} className="col-span-2 flex items-center justify-center gap-1 rounded-md border px-3 py-2 text-sm font-bold"><Archive className="h-4 w-4" />Arsipkan Surat</button></div></section></aside>
    </div>
  </div>;
};
